project_id = "wgzztskdrmikvklawllr"

[functions.stock-quote]
verify_jwt = false

[functions.quotes]
verify_jwt = false

[functions.detail]
verify_jwt = false

[functions.get-quotes]
verify_jwt = false

[functions.get-detail]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-contact]
verify_jwt = false